"""Shared, testable infrastructure for MudaRemote."""

from .config import atomic_write_json, load_json, validate_preset
from .claiming import (
    ClaimEvidence,
    ClaimOutcome,
    classify_claim_owner,
    classify_claim_text,
    cooldown_deadline,
    has_free_claim_button,
    is_claim_announcement_for_character,
)
from .coordinator import ClaimCoordinator
from .kakera import (
    calculate_kakera_power_cost,
    find_refreshed_component_button,
    get_kakera_emoji_targets,
    get_regular_kakera_filter_reason,
    has_op_perk_five_marker,
    has_perk_eight_discount,
    has_purple_kakera_button,
    is_character_sphere_emoji,
    kakera_embed_text,
    normalize_character_sphere_emoji,
    parse_kakera_result_amount,
    sphere_target_matches,
)
from .filters import (
    character_series_line,
    name_or_series_is_configured_wish,
    series_line_has_emoji,
)
from .runtime import (
    AUTOMATED_STAGGER_INTERVAL_SECONDS,
    CommandPacer,
    active_stagger_seconds,
    humanized_claim_refresh_deadline,
    pause_interruptible_sleep,
    prepare_active_presets,
    set_client_paused,
    split_command_batches,
    wait_until_resumed,
)
from .secrets import SecretStore
from .spheres import (
    SphereGameStatus,
    chest_red_candidates,
    choose_chest_position,
    choose_chest_reward_position,
    choose_harvest_position,
    count_harvest_bonus_clicks,
    harvest_reveal_is_free,
    normalize_sphere_emoji,
    parse_sphere_game_status,
)
from .status import (
    STATUS_FIELDS,
    ServerResetCoordinator,
    ServerResetSnapshot,
    clear_status_dirty,
    consume_tu_urgent_bypass,
    defer_tu_queries,
    initialize_status_tracking,
    looks_like_tu_status_snapshot,
    mark_status_dirty,
    parse_claim_denied_cooldown,
    record_tu_failure,
    record_tu_success,
    status_dirty_fields,
    status_message_addresses_identity,
    status_refresh_reasons,
    tu_retry_wait,
)
from .updater import UpdateError, apply_update, format_update_changelog
from .versioning import compare_versions, is_newer_version
from .webhooks import WebhookDispatcher

__all__ = [
    "ClaimCoordinator",
    "ClaimEvidence",
    "ClaimOutcome",
    "CommandPacer",
    "WebhookDispatcher",
    "AUTOMATED_STAGGER_INTERVAL_SECONDS",
    "SecretStore",
    "SphereGameStatus",
    "STATUS_FIELDS",
    "ServerResetCoordinator",
    "ServerResetSnapshot",
    "UpdateError",
    "apply_update",
    "format_update_changelog",
    "active_stagger_seconds",
    "humanized_claim_refresh_deadline",
    "atomic_write_json",
    "calculate_kakera_power_cost",
    "find_refreshed_component_button",
    "get_kakera_emoji_targets",
    "get_regular_kakera_filter_reason",
    "character_series_line",
    "classify_claim_owner",
    "classify_claim_text",
    "chest_red_candidates",
    "choose_chest_position",
    "choose_chest_reward_position",
    "choose_harvest_position",
    "count_harvest_bonus_clicks",
    "clear_status_dirty",
    "consume_tu_urgent_bypass",
    "compare_versions",
    "cooldown_deadline",
    "defer_tu_queries",
    "has_free_claim_button",
    "harvest_reveal_is_free",
    "initialize_status_tracking",
    "is_claim_announcement_for_character",
    "is_newer_version",
    "has_perk_eight_discount",
    "has_op_perk_five_marker",
    "has_purple_kakera_button",
    "is_character_sphere_emoji",
    "kakera_embed_text",
    "normalize_character_sphere_emoji",
    "parse_kakera_result_amount",
    "sphere_target_matches",
    "load_json",
    "looks_like_tu_status_snapshot",
    "mark_status_dirty",
    "parse_claim_denied_cooldown",
    "name_or_series_is_configured_wish",
    "normalize_sphere_emoji",
    "pause_interruptible_sleep",
    "prepare_active_presets",
    "parse_sphere_game_status",
    "record_tu_failure",
    "record_tu_success",
    "set_client_paused",
    "series_line_has_emoji",
    "split_command_batches",
    "status_dirty_fields",
    "status_message_addresses_identity",
    "status_refresh_reasons",
    "tu_retry_wait",
    "validate_preset",
    "wait_until_resumed",
]
